cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - "node_modules"

stages:
  - deps
  - test
  - build
  - publish

deps:
  type: deps
  script:
    - npm install

test:
  type: test
  image: alekzonder/puppeteer
  script:
    - npm run test:e2e

build:
  type: build
  script:
    - sed -i -e "s/@version@/$CI_COMMIT_TAG/g" src/options.object.js
    - npm run build
  artifacts:
    paths:
      - ./dist/

publish:
  type: publish
  only:
    - tags
  script:
    - AWS_ACCESS_KEY_ID=$AWS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET BUCKET_NAME=$BUCKET_NAME DEPLOY_PATH=$DEPLOY_PATH ./bin/deploy.sh
    - npm --no-git-tag-version version $CI_COMMIT_TAG
    - NPM_PUBLISH_AUTH_TOKEN=$NPM_PUBLISH_AUTH_TOKEN ./bin/publish-to-npm.sh
